### ISSUE TITLE
Download others formats

### ISSUE THREAD

**Issue by tgmarinho** [aboullaite/SpringBoot-Excel-Csv#2]
Hello @aboullaite  

When I run localhost:8080/ download, only download csv, how can I set up to download excel or pdf?

When I change the order in the class: WebConfig.java:

```
 resolvers.add(excelViewResolver());
        resolvers.add(csvViewResolver());
        resolvers.add(pdfViewResolver());
```
then download excel, how can I choose the resolver ?

**Comment by aboullaite** [comment]
Hi @tgmarinho,

You should add extension to the url. for example if you want to download you've to use: `localhost:8080/download.pdf`.

More details here: https://aboullaite.me/spring-boot-excel-csv-and-pdf-view-example/

**Comment by tgmarinho** [comment]
Thank you @aboullaite the implementations is very amazing! thanks for share! =)
Congratulations!
